import { Outfit, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";
import AppQueryClientProvider from "./QueryClientProvider";

const OutfitFont = Outfit({
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${OutfitFont.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AppQueryClientProvider>
          <Navbar />
          <main>
            {children}
          </main>
          <Footer/>
        </AppQueryClientProvider>
      </body>
    </html>
  );
}
